services:
  telegraf_test:
    image: telegraf:latest
    container_name: telegraf_test
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    command:
      - --test

  timescaledb_pgtap:
    image: timescale/timescaledb:latest-pg17-pgtap
    container_name: timescaledb-pgtap
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metrics
    volumes:
      - timescaledb_data_pgtap:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]

  migrate_test:
    image: migrate/migrate:latest
    container_name: migrate_test
    depends_on:
      timescaledb_pgtap:
        condition: service_healthy
    volumes:
      - ./timescaledb/migrations:/migrations
    entrypoint: [ "migrate", "-path", "/migrations", "-database", "postgres://postgres:postgres@timescaledb_pgtap:5432/metrics?sslmode=disable", "up" ]

volumes:
  timescaledb_data_pgtap:
